In [1]:
import numpy as np
import pcmdpy_gpu as ppy
import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline

In [2]:
ppy.__version__

'0.8.4'

In [3]:
f = ppy.instrument.default_m31_filters()
iso_model = ppy.isochrones.Isochrone_Model(f)

In [4]:
driv = ppy.driver.Driver(iso_model, gpu=True)

Please wait while the GPU states are initialized

In [5]:
!nvidia-smi

Thu Jan 24 16:11:59 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.79       Driver Version: 410.79       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K40m          Off  | 00000000:42:00.0 Off |                    0 |
| N/A   49C    P0    77W / 235W |    662MiB / 11441MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

In [6]:
gal = ppy.galaxy.TauSimple(np.array([0., -2., 2., 5.]), dmod=24.)

In [7]:
%%time
pcmd_2, im_2 = driv.simulate(gal, 1024, fixed_seed=False)

CPU times: user 1.77 s, sys: 429 ms, total: 2.2 s
Wall time: 2.58 s


In [8]:
%%time
pcmd_3, im_3 = driv.simulate(gal, 1024, fixed_seed=True)

CPU times: user 1.71 s, sys: 397 ms, total: 2.11 s
Wall time: 2.11 s


In [13]:
ppy.gpu_utils.pycuda.characterize.sizeof('curandStateXORWOW', '#include <curand_kernel.h>')

48

In [11]:
b = driv.fixed_states.copy()

In [14]:
b.gpudata

In [15]:
driv.fixed_states.gpudata

In [13]:
ppy.gpu_utils.pycuda.gpuarray.GPUArray((1024*1024), np.int32, gpudata=b.gpudata)

array([ 304825761, 1066415774,  766393452, ...,  771236125,  792620169,
       1488804138], dtype=int32)

In [13]:
ppy.gpu_utils.pycuda.gpuarray.GPUArray((1024*1024), np.int32, gpudata=b.gpudata)

array([ 304825761, 1066415774,  766393452, ...,  771236125,  792620169,
       1488804138], dtype=int32)

In [10]:
a = ppy.gpu_utils.cuda.mem_alloc(driv.fixed_states.size)

In [34]:
a

In [35]:
driv.fixed_states.gpudata

In [31]:
ppy.gpu_utils.cuda.memcpy_dtod_async(a, driv.fixed_states.gpudata, int(driv.fixed_states.size))

In [33]:
ppy.gpu_utils.pycuda.gpuarray.GPUArray((1024*1024), np.int32, gpudata=a)

array([ 304825761, 1066415774,  766393452, ...,  771236125,  792620169,
       1488804138], dtype=int32)

In [ ]:
ppy.gpu_utils.

In [ ]:
ppy.plotting.plot_pcmd(pcmd_2);

In [12]:
%%time
pcmd_3, im_3 = driv.simulate(gal, 2048, fixed_seed=True)

CPU times: user 5.94 s, sys: 2.1 s, total: 8.04 s
Wall time: 8.47 s


In [13]:
%%time
pcmd_3, im_3 = driv.simulate(gal, 2048, fixed_seed=True)

CPU times: user 5.77 s, sys: 2.04 s, total: 7.81 s
Wall time: 7.81 s


In [ ]:
%%time
pcmd_3, im_3 = driv.simulate(gal, 4096, fixed_seed=True)

In [15]:
from tqdm import tqdm

In [16]:
for i in tqdm(range(10)):
    pcmd_1, im_1 = driv.simulate(gal, 1024, fixed_seed=True)

100%|██████████| 10/10 [00:20<00:00,  2.04s/it]
